package corbaConversion;


/**
* corbaConversion/IconversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* jeudi 23 novembre 2023 09 h 34 WAT
*/

public interface IconversionRemoteOperations 
{
  double convertirMontnant (double mt);
} // interface IconversionRemoteOperations
